#!/bin/bash

# http://www.thegeekstuff.com/2010/04/unix-tar-command-examples

# move file from downloads to /usr/local with new name

set -e

if [ -z "$1" ];then 
  printf "\nYou need to specify the file to move\n"
  exit 2
fi

# head gets the first part of a filename from first line(b/c of -1)
# also note that head counts in reverse, so -1 is first file name, -2 is second
# cut takes the first field after splitting input on / 
DIR_NAME=`tar -tzf $1 | head -1 | cut -f1 -d"/"`
echo $DIR_NAME
tar xvfz $1
sudo mv $DIR_NAME /usr/local/$2
rm -rf $1
