#!/bin/sh
cd $1
tl="$(git ls-files | xargs cat | wc -l)"
if [ "$2" != "" ];
then
  ll="$(git ls-files | grep $2 | xargs cat | wc -l)"
  RESULT=$(echo "scale=2; $ll/$tl" | bc -l)
  percent=$(echo "$RESULT * 100" | bc -l)
  echo "$ll $2 lines; $percent percent of repo"
else
  echo "total lines in git repo = $tl"
fi

