#!/bin/bash

# auto-generates content of web page needed for homework, 
# rather than manually typing it

array=( "$@" )
arraylength=${#array[@]}

if [ $arraylength -eq 0 ]; then
  echo "array[0] must be hw folder name, rest of array is sketch folder file names"
  exit 1
fi

# homework name and directory
HOMEWORK_NAME=${array[0]}

echo "Daniel Evans CS276 $HOMEWORK_NAME" >> output.txt

for (( i=2; i<${arraylength}+1; i++ ));
do
    sketchName=${array[$i-1]}
    echo  -e "  $sketchName

  * {{:cs276:a16:$sketchName.png?200|}}
  * [[http://hive.sewanee.edu/evansdb0/cs276/$HOMEWORK_NAME/$sketchName/]] \n" >> output.txt
done

gedit output.txt
rm output.txt


