#!/usr/bin/env bash

cd ~/temp/temp
sudo apt-get install php7.0-mbstring # mbstring extension
sudo apt-get install php7.0-curl # curl extension
sudo apt-get install php7.0-common # PDO extension
sudo apt-get install php7.0-xml #xml extension 

# download installer for composer 
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
# Verify the installer's SHA-384
php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

# this installs composer to user's bin dir and names file "composer"
php composer-setup.php --install-dir=temp --filename=composer

# deletes installer 
php -r "unlink('composer-setup.php');"

# installs laravel
composer global require "laravel/installer"

RANDOM=$(( ( RANDOM )  + 1 ))
# creates a new laravel project, named hellothere_$RANDOM_NUM$
laravel new hellothere_$RANDOM

# if it worked correctly, the last line of the output should say
# "Application ready! Build something amazing."
