#!/bin/bash

cd

sudo apt-get update
sudo apt-get install php7.0
sudo apt-get install php7.0-mbstring # mbstring extension
sudo apt-get install php7.0-curl # curl extension
sudo apt-get install php7.0-common # PDO extension
sudo apt-get install php7.0-zip
sudo apt-get install php7.0-xml #xml extension 
sudo apt-get install php7.0-dom

# mysql 
sudo apt install mysql-server mysql-client php7.0-mysql


# nodejs
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential

# phpstorm is installed in home directory
# PhpStorm-162.2380.11
wget https://download.jetbrains.com/webide/PhpStorm-2016.2.2.tar.gz && tar xvfz PhpStorm-2016.2.2.tar.gz && rm PhpStorm-2016.2.2.tar.gz

mkdir bin

# install composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

php -r "if (hash_file('SHA384', 'composer-setup.php') === 'aa96f26c2b67226a324c27919f1eb05f21c248b987e6195cad9690d5c1ff713d53020a02ac8c217dbf90a7eacc9d141d') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

php composer-setup.php --install-dir=bin --filename=composer

php -r "unlink('composer-setup.php');"

cd

# install laravel installer 
composer global require "laravel/installer"

